package providers

const (
	ADMIN_GAME_PAGINATION = 5
	ADMIN_PROMO_PAGINATION = 5
	ADMIN_USER_PAGINATION = 5
	GAME_SEARCH_LIMIT = 5
	GAME_SEARCH_PAGE_LIMIT = 10

	COMMUNITY_ARTWORK_PAGINATION = 5
	COMMUNITY_GAME_REVIEW_PAGINATION = 5

	INVENTORY_PAGINATION = 20
	MARKET_LIST_PAGINATION = 5
)
